# Generated by Django 4.2.2 on 2023-06-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='voice',
        ),
    ]
